### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by DOsinga** [buckinha/DiamondSquare#2]
Thanks for the implementation, this is very useful. If you would change some of the '/' to '//' to make them integer division, the code would also work for Python 3.

**Comment by buckinha** [comment]
Sorry i never saw this. Had been neglecting my github for a while, obviously. I'm brushing this up now, and making it py3 compatible.

**Comment by DOsinga** [comment]
Yeah no worries. Happy to send a code review fi you wanted to

**Comment by buckinha** [comment]
You're welcome to try it out if you like. Made breaking changes here.
PR is here: https://github.com/buckinha/DiamondSquare/pull/3

**Comment by buckinha** [comment]
Tests are passing on my windows and mac machines, so i'm calling that good for the night. I've pushed to master, and the library now supports only Py3
